name: CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate experiments
    runs-on: ubuntu-latest
    steps:
      - name: Use latest Node version
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Enable corepack
        run: corepack enable
      - name: Enable git autocrlf
        run: git config --global core.autocrlf input
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Validate all experiments
        run: yarn workspaces foreach --all --parallel run validate
