name: CI

on:
  push:
    paths-ignore:
      - 'results/**'
      - 'visualizer/**'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.gitattributes'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.x

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Enable corepack
        run: corepack enable
      - name: Ensure line endings are consistent
        run: git config --global core.autocrlf input
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --immutable
      - name: Validate experiments
        run: |
          yarn plugin import workspace-tools
          yarn workspaces foreach run validate
