name: CI

on:
  push:
    paths-ignore:
      - 'results/**'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.gitattributes'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: corepack enable
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - run: yarn install --immutable
      - run: yarn workspaces foreach --all --parallel jbr generate-combinations
      - run: yarn workspaces foreach --all --parallel jbr validate
