name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_NODE_VERSION: 23.x

jobs:
  validate:
    name: Validate experiments
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.DEFAULT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - name: Enable corepack
        run: corepack enable
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --immutable
      - name: Validate experiments
        run: yarn workspaces foreach --all --parallel --include 'experiments/*' run validate
