name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_NODE_VERSION: 24.x

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experiment:
          - ltqp-solid-bloom-filters
          - ltqp-solid-default
          - ltqp-solid-join-restart
          - wikidata-graph-split
    steps:
      - name: Use Node.js ${{ env.DEFAULT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - name: Enable corepack
        run: corepack enable
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --immutable
      - name: Validate experiment
        run: yarn run validate
        working-directory: experiments/${{ matrix.experiment }}
