name: LTQP Solid Default

on:
  push:
    paths:
      - .github/workflows/ltqp-solid-default.yml
      - experiments/ltqp-solid-default/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Benchmark
    strategy:
      fail-fast: true
      matrix:
        engine:
          - default
        fragmentation:
          - default
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Enable corepack
        run: corepack enable
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --immutable
      - name: Generate dataset and queries
        run: |
          yarn solidbench generate \
            --cwd $(pwd)/generated \
            --enhancementConfig ../input/solidbench/enhancer.json \
            --queryConfig ../input/solidbench/queries.json \
            --validationConfig ../input/solidbench/validation.json \
            --fragmentConfig ../input/solidbench/fragmenter-${{ matrix.fragmentation }}.json
        working-directory: experiments/ltqp-solid-default
      - name: Prepare containers
        env:
          COMUNICA_CONFIG: ${{ matrix.engine }}
        run: docker compose --file experiments/ltqp-solid-default/input/compose.yml create
      - name: Start containers
        env:
          COMUNICA_CONFIG: ${{ matrix.engine }}
        run: docker compose --file experiments/ltqp-solid-default/input/compose.yml start
      - name: Execute queries
        run: |
          yarn sparql-benchmark-runner \
            --endpoint http://localhost:4000/sparql \
            --queries ./generated/out-queries \
            --replication 20 \
            --warmup 1 \
            --timeout 150 \
            --output ./output/${{ matrix.engine }}-${{ matrix.fragmentation }}.csv
        working-directory: experiments/ltqp-solid-default
      - name: Stop containers
        env:
          COMUNICA_CONFIG: ${{ matrix.engine }}
        if: always()
        run: docker compose --file experiments/ltqp-solid-default/input/compose.yml stop
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.engine }}-${{ matrix.fragmentation }}
          path: experiments/ltqp-solid-default/output
          if-no-files-found: error
